### ISSUE TITLE
smaller css

### ISSUE THREAD

**Issue by Aranjedeath** [cferdinandi/tabby#82]
I'm not sure if this is a bug or not, but I just wanted to give back based on my use of the project.

Because I already have a normalize.css loaded, I was able to delete almost the entire css. The following leaves bit-exact perfectly functioning tabby. 

```CSS
.js-tabby .tabs-pane:focus {
    outline: none
}

.js-tabby .tabs-pane:not(.active) {
    display: none;
}
```

hope it helps

it's live on [my site](https://explodie.org/aranjepack.html)
